version: '3'

services:
  web:
    container_name: nginx_compose
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - test_net
    tty: true
  db:
    container_name: mysql_compose
    image: mysql:5.7
    env_file: envFile.txt
    ports:
      - "3306:3306"
    networks:
      - test_net

networks:
  test_net: